<?php
/**
 * Created by PhpStorm.
 * User: медведь
 * Date: 10.08.2017
 * Time: 23:00
 */
namespace app\components;
use yii\base\Widget;
use Yii;
use app\models\LoginForm;
use app\models\User;
use yii\web\Controller;

class LoginWidget extends Widget
{
    public $views; // Параметр виджета для определения шаблона
    public $model; // модель пользователя


    /**
     * Определяем страницу
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ( $this->views === null )
        {
            $this->views = 'login';
        }
        $this->views .= '.php';
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        if (!Yii::$app->user->isGuest) {

            $model = User::find()->where(['id' => Yii::$app->user->id])->one();
            return $this->catToTemplateUser($model);

        } else {

            $model = new User();
            return $this->catToTemplate($model);

        }
    }

        // Передача в шаблон параметров пользователя
        protected function catToTemplate($model)
    {

        ob_start();
        include __DIR__ . '/views/' . $this->views;
        return ob_get_clean();


    }
        // передача в шаблон модели пользователя
        protected function catToTemplateUser($model)
    {
        ob_start();
        include __DIR__ . '/views/' . $this->views;
        return ob_get_clean();


    }

}